### ISSUE TITLE
Implement curvature

### ISSUE THREAD

**Issue by wkearn** [TopoToolbox/libtopotoolbox#103]

**Comment by Teschl** [comment]
I will work on this issue now.

**Comment by Teschl** [comment]
@wkearn I got back to this issue last week, and I think we'll need to choose how we want to handle the `meanfilt` option (and maybe how we use convolution in general)

1. Apply the mean filter function in the curvature function. Will also need another array with the size of dims.
2. Apply separate mean filter function it in the python version, for example (either in the grid.cpp or the actual python function)

Since we are creating the [mean filter function](https://github.com/wschwanghart/topotoolbox/blob/master/%40GRIDobj/filter.m) anyway, would it make sense to also create a conv2 version of our own? It seems go get used in a lot of functions.

**Comment by wkearn** [comment]
> @wkearn I got back to this issue last week, and I think we'll need to choose how we want to handle the `meanfilt` option (and maybe how we use convolution in general)
> 
> 1. Apply the mean filter function in the curvature function. Will also need another array with the size of dims.

One trick that immediately occurs to me: doing two convolutions (i.e. `conv2(conv2(dem,kernel1),kernel2)` should be equivalent to doing a single convolution with a kernel that is the convolution of the two kernels. You have to be careful to get the boundary conditions and orientations of the kernels right, but you could compute one kernel that represents applying the mean filter, then applying the derivative computations, and one that just does the derivatives without the mean filter. Of course you need to to this separately for the two first derivative kernels and the three second derivative kernels.

>  2. Apply separate mean filter function it in the python version, for example (either in the grid.cpp or the actual python function)
> Since we are creating the [mean filter function](https://github.com/wschwanghart/topotoolbox/blob/master/%40GRIDobj/filter.m) anyway, would it make sense to also create a conv2 version of our own? It seems go get used in a lot of functions.

@wschwanghart and I actually discussed this a little yesterday: it might make sense to use `scipy`'s [image processing functions](https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.convolve.html#scipy.ndimage.convolve) to handle things like convolution in pytopotoolbox. Their implementations are likely to be better optimized than anything we come up with, and would probably make handling different edge cases like we ran into with `acv` easier. We do lose some degree of uniformity between the different packages, and we add a different dependency for every package, but the tradeoff might be worth it for now.

So I am thinking that a good strategy for `curvature` would be to try to get it working in pytopotoolbox with `scipy` functions first. Then we can see what that interface looks like and figure out if we really want to build our own convolution solution. Does that sound achievable?

**Comment by wschwanghart** [comment]
Yes, @wkearn, you are perfectly right. We need to balance "reinventing the wheel" and "software dependencies". For some of these crucial operations such as convolutions, I think they are so common and so much applied in different fields of numerical analysis that they are very unlikely to break. At the same time, these algorithms have been highly optimized. In MATLAB, I am using conv2 and in scipy, there is convolve2d as part of the [signal](https://docs.scipy.org/doc/scipy/reference/signal.html) package. Also, the [ndimage](https://docs.scipy.org/doc/scipy/reference/ndimage.html) package has some interesting stuff like image morphological operations. Some of these will overlap with some of the functions that we have implemented ourselves in C.

**Comment by Teschl** [comment]
> So I am thinking that a good strategy for curvature would be to try to get it working in pytopotoolbox with scipy functions first. 

I think I already completed the function on python. Using SciPy's `convolve` function makes this very straight forward. Documentation and error handling are still missing, but the functionality should be there. I had to add an epsilon to avoid having to divide by zero.

```python
def curvature(self, ctype='profc', meanfilt=False):

        if meanfilt:
            kernel = np.ones((3, 3)) / 9
            dem = convolve(self.z, kernel, mode='nearest')
        else:
            dem = self.z

        kernel_fx = np.array(
            [[-1, 0, 1], [-1, 0, 1], [-1, 0, 1]]) / (6 * self.cellsize)
        kernel_fy = np.array(
            [[1, 1, 1], [0, 0, 0], [-1, -1, -1]]) / (6 * self.cellsize)

        fx = convolve(dem, kernel_fx, mode='nearest')
        fy = convolve(dem, kernel_fy, mode='nearest')

        kernel_fxx = np.array(
            [[1, -2, 1], [1, -2, 1], [1, -2, 1]]) / (3 * self.cellsize**2)
        kernel_fyy = kernel_fxx.T
        kernel_fxy = np.array(
            [[-1, 0, 1], [0, 0, 0], [1, 0, -1]]) / (4 * self.cellsize**2)

        fxx = convolve(dem, kernel_fxx, mode='nearest')
        fyy = convolve(dem, kernel_fyy, mode='nearest')
        fxy = convolve(dem, kernel_fxy, mode='nearest')

        epsilon = 1e-10
        if ctype == 'profc':
            denominator = (fx**2 + fy**2) * (1 + fx **
                                             2 + fy**2)**(3/2) + epsilon
            curvature = - (fx**2 * fxx + 2 * fx * fy * fxy + fy **
                           2 * fyy) / denominator
        elif ctype == 'tangc':
            denominator = (fx**2 + fy**2) * (1 + fx **
                                             2 + fy**2)**(1/2) + epsilon
            curvature = - (fy**2 * fxx - 2 * fx * fy * fxy + fx **
                           2 * fyy) / denominator
        elif ctype == 'planc':
            denominator = (fx**2 + fy**2)**(3/2) + epsilon
            curvature = - (fy**2 * fxx - 2 * fx * fy * fxy + fx **
                           2 * fyy) / denominator
        elif ctype == 'meanc':
            denominator = 2 * (fx**2 + fy**2 + 1)**(3/2) + epsilon
            curvature = -((1 + fy ** 2) * fxx - 2 * fxy * fx * fy +
                          (1 + fx ** 2) * fyy) / denominator
        elif ctype == 'total':
            curvature = fxx**2 + 2 * fxy**2 + fyy**2

        result = copy.copy(self)
        result.z = curvature
        return result
```

Resulting plot with a bit of hillshade:
![image](https://github.com/user-attachments/assets/9d1818de-ba69-48ab-8940-6fc1198c8aa9)

**Comment by wkearn** [comment]
Let's add this to pytopotoolbox. I think depending on scipy's convolution operations is a better solution for now. We could also implement `acv` and a lot of the other filtering operations such as `filter`, `dilate`, `erode`, `evansslope` this way with relatively little effort.
